### ISSUE TITLE
'light' theme makes search box unreadable

### ISSUE THREAD

**Issue by jnr101** [matthewlilley/sushiswap-analytics#6] opened 2020-11-03 19:38 UTC
When the 'light' theme is selected, the search box turns white  (the rest stays dark). But the text in the search box is also white, which makes it unreadable. 'light' theme is currently the default...

**Comment by matthewlilley** [comment] 2020-11-11 13:32
@jnr101 What browser and OS are you using?

**Comment by jnr101** [comment] 2020-11-15 18:55
@matthewlilley I am using chrome and safari, both on MacOS (IOS). Also tested on my iphone, same result. It seems to be something with Mac :-) I checked on a windows systems and there the light theme is correct

**Comment by matthewlilley** [comment] 2020-11-16 21:05
@jnr101 I'm working on a large update to the UI at the moment which I'm hoping to push through before the end of the week, I'll be sure to test on a Mac environment to see what the issue is beforehand.

**Comment by matthewlilley** [comment] 2020-11-24 01:41
@jnr101 Ah, I stumbled across this Today while my system was set to default dark mode for apps. I'll include a fix for this shortly. Thanks for the report!

**Closed by matthewlilley** 2020-11-24 01:41 UTC
